name: Update Contributors in README

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  contrib:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Update Contributors
        uses: mindandcode/contributors-list-action@v2.5
        with:
          readme_path: "README.md"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
